### ISSUE TITLE
needed simple example

### ISSUE THREAD

**Issue by philschmid** [usefulio/serverless-kubeless-offline#3]
Hello,

i came across this plugin and thought nice this is excatly what i needed to develope kubeless offline. But i have an issue i don t understand how to use this plugin. I tested everything. I have an function with the route '/hello' and the server ist running on localhost:3000 so i thought i can access it on localhost:3000/hello but i cant. 

Can you show me a simple example how to access the functions?

**Comment by remacr** [comment]
The problem I'm having is when I add the events tag to place a custom path.

For example, this works fine:
```yml
...
functions:
  hello:
    handler: index.hello
...
```

And the `serverless offline start` output is:
```
Serverless: Routes:
Serverless: [
  {
    "file": "index",
    "function": "hello",
    "route": "hello"
  }
]
```

I'm able to hit http://localhost:3000/hello correctly, but when I do:

```yml
...
functions:
  hello:
    handler: index.hello
    events:
      - path: /api/v1/hello
...
```

The output is:

```
Serverless: Routes:
Serverless: []
```
